"""build123d builds the same parts KOMPAS built.

ENGINE-MIG-006. The migration's premise is that the engine underneath CAD-IR can
be replaced without changing what a customer gets, and that premise is only worth
anything if it is checked. So every fixture the KOMPAS engine was accepted on is
built again here and measured against the numbers that acceptance recorded.

Two rules make this a parity test rather than a self-consistency one.

*The expected numbers are not computed from the build.* They are transcribed from
`docs/acceptance/` — what KOMPAS measured — or derived by arithmetic from the
drawing. A table generated by the engine under test would agree with it about
anything it got wrong, which is the same argument ADR-018 makes about
expectations and the one `verify.py` makes about reading a mesh back as a file.

*A difference is stated, not tolerated.* The two kernels do not model topology
identically, and the one place they disagree — the seam edge OpenCascade carries
on a closed cylindrical face — is written down as a rule with its own test rather
than hidden inside a fudged edge count.

These need the CAD library, so they skip where it is absent. That keeps the suite
runnable on a machine with no engine at all, which is the property ENGINE-MIG-002
set up; CI runs them in the job that installs the worker's own requirements.
"""

from __future__ import annotations

import collections
import json
from dataclasses import dataclass, field
from pathlib import Path

import pytest

pytest.importorskip("build123d", reason="the CAD engine is not installed")

from cad_ir.canonical_validator import validate_canonical  # noqa: E402

from cad_engine_build123d.adapter import build  # noqa: E402
from cad_engine_build123d.adapter import build_part  # noqa: E402
from cad_engine_build123d.topology import read_edges, read_faces  # noqa: E402
from cad_engine_build123d.verify import Expectations, verify  # noqa: E402

FIXTURES = Path(__file__).resolve().parents[3] / "tests" / "fixtures" / "cad-ir"


@dataclass(frozen=True)
class Parity:
    """One part, and everything the other engine — or arithmetic — says it is."""

    name: str
    #: Where these numbers come from. Not decoration: a parity figure whose
    #: source cannot be named is a figure somebody typed to make a test pass.
    source: str
    bodies: int
    #: Faces by surface type. The split matters more than the total — a part with
    #: the right face count and a plane where a cylinder belongs is a wrong part.
    faces: dict[str, int]
    edges: int
    volume_mm3: float
    size_mm: tuple[float, float, float]
    #: Area of each horizontal face, by the height it sits at. A face count says
    #: the topology is right; an area says the geometry is.
    horizontal_areas: dict[float, float] = field(default_factory=dict)
    #: How many of those edges are seams — one per *closed* cylinder. A half
    #: cylinder has no seam, so this is not the cylindrical face count.
    seam_edges: int = 0
    #: Edges KOMPAS reported for the same part, where an acceptance run recorded
    #: it. Absent where none did — the seam rule is then untestable here rather
    #: than assumed.
    kompas_edges: int | None = None

    def document(self):
        return validate_canonical(json.loads((FIXTURES / self.name).read_text("utf-8")))


PARTS: tuple[Parity, ...] = (
    Parity(
        name="plate.v1_10.json",
        source="TASK-009 40 × 20 × 10 plate; a box has six faces and twelve edges",
        bodies=1,
        faces={"planar": 6},
        edges=12,
        volume_mm3=40 * 20 * 10,
        size_mm=(40.0, 20.0, 10.0),
        horizontal_areas={0.0: 800.0, 10.0: 800.0},
    ),
    Parity(
        name="plate-with-hole.v1_10.json",
        source="TASK-009 40 × 20 × 10 plate, one Ø6 through hole",
        bodies=1,
        faces={"planar": 6, "cylindrical": 1},
        # Twelve for the box, then two circles and a seam for the hole.
        edges=15,
        volume_mm3=40 * 20 * 10 - 3.141592653589793 * 3.0**2 * 10,
        size_mm=(40.0, 20.0, 10.0),
        horizontal_areas={
            0.0: 40 * 20 - 3.141592653589793 * 3.0**2,
            10.0: 40 * 20 - 3.141592653589793 * 3.0**2,
        },
        seam_edges=1,
    ),
    Parity(
        name="constrained-plate.v1_10.json",
        source=(
            "docs/acceptance/POSTMVP-007: 1 body, bounding box [60, 30, 8]. "
            "docs/acceptance/POSTMVP-005 recorded 8 faces and 16 edges for a "
            "60 × 30 × 8 plate with two through holes — the same topology, drilled "
            "to a different radius. The areas below are this fixture's own "
            "parameters: hole_radius 4, hole_pitch_x 20."
        ),
        bodies=1,
        faces={"planar": 6, "cylindrical": 2},
        edges=18,
        volume_mm3=60 * 30 * 8 - 2 * 3.141592653589793 * 4.0**2 * 8,
        size_mm=(60.0, 30.0, 8.0),
        horizontal_areas={
            0.0: 60 * 30 - 2 * 3.141592653589793 * 4.0**2,
            8.0: 60 * 30 - 2 * 3.141592653589793 * 4.0**2,
        },
        seam_edges=2,
        kompas_edges=16,
    ),
    Parity(
        name="lever-plate.v1_10.json",
        source="docs/acceptance/POSTMVP-006: 1 body, 17 faces (12 planar, 5 cylindrical)",
        bodies=1,
        faces={"planar": 12, "cylindrical": 5},
        # Reported by this engine and not by KOMPAS, so it is arithmetic rather
        # than a transcription: the stadium plate's two islands and two end caps
        # and the pin each close a cylinder, and each carries a seam.
        edges=39,
        # No acceptance run measured a volume. Derived from the drawing: the
        # stadium plate less two Ø5 holes, plus the hexagonal hub less the pin's
        # footprint where the two overlap, plus the Ø8 pin.
        volume_mm3=(
            (50 * 30 + 3.141592653589793 * 15.0**2 - 2 * 3.141592653589793 * 2.5**2) * 8
            + 1.5 * 3**0.5 * 10.0**2 * 4
            + 3.141592653589793 * 4.0**2 * 3
        ),
        size_mm=(80.0, 30.0, 15.0),
        # Transcribed from the POSTMVP-006 acceptance table, read back through
        # API5 from the saved M3D. Four heights, four areas, to three decimals.
        horizontal_areas={0.0: 2167.588, 8.0: 1907.781, 12.0: 209.542, 15.0: 50.265},
        # Three of the five cylinders close: the two holes and the pin. The
        # stadium's end caps are half cylinders and carry no seam.
        seam_edges=3,
        # POSTMVP-006 recorded faces but not edges.
        kompas_edges=None,
    ),
)

IDS = [part.name.removesuffix(".v1_10.json") for part in PARTS]


@pytest.fixture(scope="module", params=PARTS, ids=IDS)
def built(request):
    """Each fixture, built once and measured by several tests.

    Module-scoped because a build is the expensive part and none of these tests
    mutate the solid. Any that did would be testing something other than parity.
    """
    parity: Parity = request.param
    return parity, build_part(parity.document())


def test_the_part_is_one_solid(built):
    parity, part = built
    assert len(part.solids()) == parity.bodies, parity.source


def test_the_faces_are_the_faces_kompas_reported(built):
    parity, part = built
    counted = collections.Counter(face.surface_type for face in read_faces(part))
    assert dict(counted) == parity.faces, parity.source


def test_the_bounding_box_is_the_drawing(built):
    parity, part = built
    box = part.bounding_box()
    measured = (float(box.size.X), float(box.size.Y), float(box.size.Z))
    for axis, (was, expected) in enumerate(zip(measured, parity.size_mm)):
        # Read off the solid, so no tessellation tolerance applies. A kernel that
        # cannot place a plane to a micron has a worse problem than this test.
        assert abs(was - expected) < 1e-6, f"axis {axis}: {was} != {expected}"


def test_the_volume_is_what_the_drawing_says(built):
    """The one measurement no face count can fake.

    A part can have every face of the right kind in the right place and still be
    the wrong solid — a cut applied to the wrong side, an island built as a boss.
    Volume is the check that notices.
    """
    parity, part = built
    assert float(part.volume) == pytest.approx(parity.volume_mm3, abs=1e-3)


def test_every_horizontal_face_has_the_area_it_had_on_kompas(built):
    parity, part = built
    areas: dict[float, float] = collections.defaultdict(float)
    for face in read_faces(part):
        if face.surface_type != "planar" or face.normal is None:
            continue
        if abs(abs(face.normal[2]) - 1.0) > 1e-9:
            continue
        areas[round(face.centroid[2], 3)] += face.area_mm2

    assert sorted(areas) == sorted(parity.horizontal_areas), parity.source
    for height, expected in parity.horizontal_areas.items():
        # A thousandth of a square millimetre: the precision the acceptance table
        # was written to, and finer than any modelling error could hide under.
        assert areas[height] == pytest.approx(expected, abs=1e-3), f"z = {height}"


def test_the_edges_are_counted_and_the_difference_is_the_seam(built):
    """Where the two kernels genuinely disagree, and why it is not a defect.

    A closed cylindrical face in OpenCascade is parameterised over a period, and
    the period has to start somewhere: the surface carries a seam edge along the
    line where its parameterisation wraps. KOMPAS's face has no such edge. So a
    through hole is three edges here and two there, and the totals differ by one
    per closed cylinder — not per cylindrical face, because the stadium plate's
    end caps are half cylinders and close nothing.

    Asserted rather than absorbed, because the difference is real and a selector
    written against edges will meet it. A seam is identifiable — it is the only
    edge of a solid that touches exactly one face — so a later operation can
    exclude it deliberately instead of being surprised by it.
    """
    parity, part = built
    edges = read_edges(part)
    assert len(edges) == parity.edges, parity.source

    seams = [edge for edge in edges if edge.adjacent_face_count == 1]
    assert len(seams) == parity.seam_edges
    assert all(edge.adjacent_surface_types == ("cylindrical",) for edge in seams)

    if parity.kompas_edges is not None:
        assert len(edges) - len(seams) == parity.kompas_edges, parity.source


def test_the_exported_files_verify(built, tmp_path_factory):
    """The whole worker path, not only the solid in memory.

    Built, written, reopened by a reader that did not write them, and measured
    against the document's own expectations (ENGINE-MIG-005). A parity run that
    stopped at the in-memory solid would prove nothing about the two files that
    are the product.
    """
    parity, _ = built
    document = parity.document()
    output = tmp_path_factory.mktemp(parity.name.replace(".", "-"))
    outcome = build(document, output)

    assert [artifact.kind for artifact in outcome.artifacts] == ["STEP", "STL"]
    report = verify(output / "model.step", output / "model.stl", Expectations.of(document))
    failed = [check for check in report.checks if not check.passed]
    assert report.valid, "; ".join(f"{check.name}: {check.detail}" for check in failed)
